default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: bangui_development
  username: bigvision
  password: bigvision75
  host: localhost

test:
  <<: *default
  database: bangui_test
  username: visionary
  password: visionary75
  host: localhost

production:
  <<: *default
  database: bangui_production
  username: vision
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: localhost
